"""Registry of executable phase contracts for V.I.O.L.E.T."""

from __future__ import annotations

from .contract_types import PhaseContract

SOURCE_CONCEPT_FULL_CHAIN_STAGES: tuple[str, ...] = (
    "source_signal_adapter_inventory",
    "media_tags_adapter",
    "source_metadata_record_structured_field_adapter",
    "source_tag_observation_adapter",
    "source_name_observation_adapter",
    "source_searchable_name_assertion_adapter",
    "source_name_candidate_f7a_adapter",
    "provider_cache_adapter_or_zero_eligible_proof",
    "deterministic_blocking_key_generation",
    "deterministic_edge_graph_generation",
    "context_compatibility",
    "alias_component_context_equivalence",
    "union_component_resolution",
    "bounded_llm_pair_adjudication_planning",
    "llm_pair_selection",
    "llm_provider_availability_check",
    "llm_judgment_execution_or_blocked_before_write",
    "llm_judgment_count",
    "llm_cache_accounting",
    "llm_decisions_recorded_source_layer_only",
    "persistence_allowed_source_concept_tables",
    "mutation_proof",
    "post_commit_verification",
    "validation_pack_review_pack",
)

SOURCE_CONCEPT_ALLOWED_STATUSES: tuple[str, ...] = (
    "deterministic_only",
    "full_chain_completed",
    "full_chain_blocked_llm_unavailable",
    "full_chain_blocked_budget",
    "full_chain_inconclusive_missing_artifacts",
)

REQUIRED_CONTRACT_IDS: tuple[str, ...] = (
    "python_env_contract_v1",
    "postgres_db_contract_v1",
    "media_import_contract_v1",
    "classification_contract_v1",
    "ai_tagging_contract_v1",
    "localization_contract_v1",
    "source_metadata_contract_v1",
    "source_concept_full_chain_contract_v1",
    "review_pack_contract_v1",
    "route_audit_contract_v1",
    "public_redaction_contract_v1",
    "mutation_safety_contract_v1",
    "artifact_lifecycle_contract_v1",
    "destructive_operation_contract_v1",
    "entity_truth_bridge_contract_v1",
    "dynamic_library_sync_contract_v1",
    "phase47_s2_baseline_contract_v1",
    "production_development_separation_contract_v1",
    "s2g1x_probe_contract_v1",
    "s2g_s3a_f1_foundation_contract_v1",
    "s2g_real1_bounded_ai_tagging_validation_contract_v1",
    "s3a_pilot1_new_data_directml_chain_contract_v1",
    "s3a_prod1_operator_incremental_sync_contract_v1",
    "s3a_prod2_s3b_d1_operator_scaleup_disabled_sync_contract_v1",
)


CONTRACTS: dict[str, PhaseContract] = {
    "python_env_contract_v1": PhaseContract(
        contract_id="python_env_contract_v1",
        contract_version="1",
        phase_kind="environment_preflight",
        required_summary_fields=(
            "python_env.expected_python_checked",
            "python_env.check_python_env_passed",
            "python_env.public_executable_name",
            "python_env.executable_path_redacted",
        ),
        required_validation_commands=("scripts/check_python_env.py --expected-python <expected>",),
        provider_policy="forbidden",
        llm_policy="forbidden",
        mutation_policy="no_files_or_db",
        redaction_policy="record executable basename only in public summaries",
        failure_behavior="fail_before_any_runtime_or_test_step",
        custom_checks=("python_env",),
        description="Verifies the approved repo-local venv Python was used and public summaries do not expose full local executable paths.",
    ),
    "postgres_db_contract_v1": PhaseContract(
        contract_id="postgres_db_contract_v1",
        contract_version="1",
        phase_kind="database_identity_preflight",
        required_summary_fields=(
            "db_identity",
            "db_identity.db_resolution.password_value_recorded",
            "db_identity.db_resolution.runner_matches_app_equivalent",
        ),
        db_write_policy="identity_check_only",
        provider_policy="forbidden",
        llm_policy="forbidden",
        mutation_policy="destructive_operations_forbidden_without_destructive_operation_contract_v1",
        redaction_policy="passwords and full DB URLs must not be recorded",
        failure_behavior="fail_closed_on_missing_or_secret_db_identity",
        custom_checks=("postgres_db",),
        description="Checks DB identity and app-compatible DB URL equivalence without recording passwords.",
    ),
    "media_import_contract_v1": PhaseContract(
        contract_id="media_import_contract_v1",
        contract_version="1",
        phase_kind="media_import",
        required_summary_fields=(
            "source_root_safety_proof",
            "staging_root_safety_proof",
            "import_ledger",
            "media_counts.before",
            "media_counts.after",
            "duplicate_path_leak_proof",
            "mutation_proof",
            "rollback_recovery_notes",
        ),
        required_artifacts=("import_ledger", "mutation_proof"),
        db_write_policy="explicit_import_contract_only",
        provider_policy="forbidden",
        llm_policy="forbidden",
        mutation_policy="source_and_icloud_mutation_forbidden",
        redaction_policy="no local paths, filenames, source roots, or originals in public artifacts",
        failure_behavior="fail_closed_before_db_import_if_safety_proof_missing",
        custom_checks=("media_import",),
        description="Defines future import proof requirements. GOV3 does not run import.",
    ),
    "classification_contract_v1": PhaseContract(
        contract_id="classification_contract_v1",
        contract_version="1",
        phase_kind="classification",
        required_summary_fields=(
            "eligible_denominator",
            "classification_jobs_by_status",
            "content_class_distribution.before",
            "content_class_distribution.after",
            "mutation_proof",
        ),
        db_write_policy="allowed_classification_tables_only",
        provider_policy="forbidden",
        llm_policy="forbidden",
        mutation_policy="source_and_storage_mutation_forbidden",
        redaction_policy="public aggregate counts only",
        failure_behavior="fail_closed_on_missing_denominator_or_mutation_proof",
        custom_checks=("classification",),
        description="Defines future classification phase proof requirements. GOV3 does not run classification.",
    ),
    "ai_tagging_contract_v1": PhaseContract(
        contract_id="ai_tagging_contract_v1",
        contract_version="1",
        phase_kind="ai_tagging",
        required_summary_fields=(
            "eligible_media_denominator",
            "ai_tag_coverage.before",
            "ai_tag_coverage.after",
            "job_status_accounting",
            "model_provenance",
            "manual_truth_overwrite_proof",
            "mutation_proof",
            "public_redaction",
        ),
        db_write_policy="allowed_ai_tag_job_and_tag_suggestion_tables_only",
        provider_policy="forbidden_unless_model_local_or_explicitly_approved",
        llm_policy="forbidden_unless_translation_or_adjudication_contract_allows",
        mutation_policy="manual_or_truth_tags_must_not_be_overwritten",
        redaction_policy="public/private artifact boundary required",
        failure_behavior="fail_closed_on_missing_model_or_mutation_proof",
        custom_checks=("ai_tagging",),
        description="Defines future AI tagging proof requirements. GOV3 does not run AI tagging.",
    ),
    "localization_contract_v1": PhaseContract(
        contract_id="localization_contract_v1",
        contract_version="1",
        phase_kind="tag_localization",
        required_summary_fields=(
            "translation_source_policy",
            "provider_policy",
            "rate_limit_cache_retry_accounting",
            "translation_counts.translated",
            "translation_counts.interrupted",
            "translation_counts.rate_limited",
            "mutation_proof",
            "public_redaction",
        ),
        db_write_policy="tag_translation_tables_only",
        provider_policy="explicit_if_llm_or_external_translation_used",
        llm_policy="explicit_policy_rate_limit_cache_and_retry_required",
        mutation_policy="no_unrelated_tag_or_media_mutation",
        redaction_policy="public/private artifact boundary required",
        failure_behavior="fail_closed_on_missing_provider_or_rate_limit_accounting",
        custom_checks=("localization",),
        description="Defines future localization/translation proof requirements. GOV3 does not run localization.",
    ),
    "source_metadata_contract_v1": PhaseContract(
        contract_id="source_metadata_contract_v1",
        contract_version="1",
        phase_kind="source_metadata_extraction",
        required_summary_fields=(
            "provider_policy",
            "provider_identity",
            "request_ledger",
            "failure_ledger",
            "cache_retry_rate_limit_accounting",
            "source_metadata_write_allowlist",
            "entity_truth_proof",
            "media_tags_mutation_proof",
            "image_upload_policy",
            "public_private_artifact_boundary",
        ),
        required_artifacts=("request_ledger", "failure_ledger"),
        db_write_policy="source_metadata_write_allowlist_only",
        provider_policy="explicit_provider_identity_no_secret_logging_required",
        llm_policy="forbidden_unless_contract_extends_provider_policy",
        mutation_policy="no_entity_truth_no_media_tags_no_image_upload_without_separate_approval",
        redaction_policy="no provider credentials, local paths, filenames, or source roots in public artifacts",
        review_pack_policy="required_when_output_influences_route_decisions",
        failure_behavior="fail_closed_on_missing_provider_or_ledger_proof",
        custom_checks=("source_metadata",),
        description="Defines future source metadata extraction proof requirements. GOV3 does not run providers.",
    ),
    "dynamic_library_sync_contract_v1": PhaseContract(
        contract_id="dynamic_library_sync_contract_v1",
        contract_version="1",
        phase_kind="dynamic_library_sync_product_foundation",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "dynamic_sync.schema.tables",
            "dynamic_sync.identity.source_item_identity",
            "dynamic_sync.default_off_policy.auto_sync_enabled",
            "dynamic_sync.default_off_policy.manual_sync_enabled",
            "dynamic_sync.threshold.default",
            "dynamic_sync.pending_counts.visible",
            "dynamic_sync.dry_run_no_import",
            "dynamic_sync.source_root_safety.passed",
            "ai_localization.chain_verified",
            "ai_localization.ai_tagging_auto_localization_default_enabled",
            "proper_noun_safeguards.preserved",
            "validation.focused_tests_passed",
            "validation.browser_validation.status",
            "safety.full_production_import",
            "safety.production_db_import",
            "safety.full_ai_tagging_run",
            "safety.full_llm_localization_batch",
            "safety.provider_calls",
            "safety.sourceconcept_or_entity",
            "safety.source_icloud_mutation",
            "safety.destructive_cleanup",
        ),
        required_validation_commands=(
            "pytest tests/test_dynamic_library_sync.py tests/test_ai_tagging_localization_gate.py -v",
            "npx playwright test tests/e2e/admin-content.spec.ts --project=edge",
        ),
        forbidden_stages=(
            "full_production_import",
            "production_db_import",
            "full_ai_tagging_run",
            "full_llm_localization_batch",
            "provider_call",
            "sourceconcept_resolver",
            "entity_bridge",
            "confirmed_assignment_creation",
            "source_icloud_mutation",
            "destructive_cleanup",
        ),
        db_write_policy="schema_and_dynamic_sync_state_only_no_production_import",
        provider_policy="forbidden",
        llm_policy="readiness_only_no_llm_batch",
        mutation_policy="no_source_icloud_app_storage_or_truth_path_mutation",
        redaction_policy="public reports must not expose source paths, filenames, secrets, DB URLs, or API keys",
        failure_behavior="fail_closed_before_claiming_target_met_or_safe_to_merge",
        custom_checks=("dynamic_library_sync",),
        description="Phase 4.7-S1 product foundation contract for durable dynamic sync state, default-off production writes, AI/localization readiness, and proper-noun safeguards.",
    ),
    "phase47_s2_baseline_contract_v1": PhaseContract(
        contract_id="phase47_s2_baseline_contract_v1",
        contract_version="1",
        phase_kind="baseline_full_import_ai_localization",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "gate0.status",
            "gate0.schema.ensure.status",
            "gate0.schema.after.tables_missing",
            "gate0.backup_recovery.proof_exists",
            "gate0.backup_recovery.valid",
            "gate0.input_root_registration.registered_count",
            "readiness.passed",
            "readiness.blockers",
            "readiness.python_env.check_python_env_passed",
            "readiness.db_identity.db_resolution.runner_matches_app_equivalent",
            "readiness.dynamic_schema.tables_missing",
            "dynamic_sync_dry_run.status",
            "dynamic_sync_dry_run.executed",
            "import_results.status",
            "import_results.executed",
            "classification_results.status",
            "classification_results.executed",
            "ai_tagging_results.status",
            "ai_tagging_results.executed",
            "localization_results.status",
            "localization_results.executed",
            "localization_results.llm_called",
            "proper_noun_review.unreviewed_llm_aliases_excluded_from_search",
            "browser_validation.status",
            "private_artifacts.private_artifacts_committed",
            "public_redaction.passed",
            "safety.no_source_icloud_mutation",
            "safety.no_cleanup_delete_reset_drop_truncate",
            "safety.no_db_import",
            "safety.no_classification",
            "safety.no_ai_tagging",
            "safety.no_llm_call",
            "artifact_lifecycle.artifacts",
        ),
        db_write_policy="gate1_blocks_before_import; execute requires explicit S2 confirmation",
        provider_policy="forbidden_before_gate1; LLM only for tag localization after explicit approval",
        llm_policy="allowed_for_general_meta_tag_localization_after_gate1_and_approval",
        mutation_policy="source_icloud_mutation_forbidden; app storage/db writes only after gates",
        redaction_policy="public report aggregate-only with no paths, filenames, secrets, or DB URLs",
        failure_behavior="fail_closed_on_readiness_blockers_before_execution",
        custom_checks=("phase47_s2_baseline",),
        description="Phase 4.7-S2 controlled baseline gate for full import, classification, AI tagging, tag localization, and browser validation.",
    ),
    "production_development_separation_contract_v1": PhaseContract(
        contract_id="production_development_separation_contract_v1",
        contract_version="1",
        phase_kind="post_s2_mainline_governance",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "governance_lanes.production.explicit",
            "governance_lanes.development.explicit",
            "development_lane.allowed_data_sources",
            "development_lane.production_db_as_fixture",
            "development_lane.production_storage_as_fixture",
            "development_lane.production_source_roots_as_fixture",
            "development_lane.production_private_ledgers_as_fixture",
            "production_promotion.required_for_production_writes",
            "production_promotion.enabled",
            "production_write_gates.import_classification_ai_localization_requires_promotion",
            "production_source_root_write_gates.clean_identity_required",
            "production_source_root_write_gates.backup_proof_required",
            "schema_setup_gates.identity_gates_required",
            "schema_setup_gates.no_schema_setup_when_identity_blocked",
            "artifact_boundary.public_reports_aggregate_only",
            "artifact_boundary.public_reports_path_redacted",
            "artifact_boundary.public_redaction_contract_passed",
            "artifact_boundary.private_ledgers_local_ignored",
            "artifact_boundary.private_ledgers_committed",
            "phase_boundaries.current_phase",
            "phase_boundaries.next_recommended_phase",
            "phase_boundaries.future_mentions_are_non_authorizing",
            "validation.focused_tests_passed",
        ),
        required_validation_commands=(
            "python scripts/check_phase_contract.py --contract production_development_separation_contract_v1 --summary tests/fixtures/phase_contracts/mock_pd1a_governance_summary.json",
            "pytest tests/test_phase_contracts.py tests/test_pd1a_mainline_governance.py -v",
        ),
        forbidden_stages=(
            "s3",
            "s3a",
            "s3b",
            "provider_call",
            "pixiv",
            "gallery_dl",
            "saucenao",
            "google_vision",
            "sourceconcept_r1r",
            "sourceconcept_r2",
            "entity_bridge",
            "confirmed_assignment_creation",
            "gpu_benchmark",
            "production_import",
            "production_classification",
            "production_ai_tagging",
            "production_localization",
            "automatic_production_sync",
            "desired_media_backfill",
        ),
        db_write_policy="production writes require explicit promotion mode; feature branches use dev/test DB/storage, fixtures, or restored snapshots",
        provider_policy="forbidden in PD1-A; future provider/Pixiv/source metadata work requires separate approval",
        llm_policy="forbidden in PD1-A",
        mutation_policy="no production DB, app-storage, source-root, iCloud, cleanup, or destructive mutation",
        redaction_policy="public reports aggregate-only and path-redacted; private ledgers remain local ignored artifacts",
        failure_behavior="fail_closed_on_production_fixture_use_or_production_write_without_promotion",
        custom_checks=("production_development_separation",),
        description="Post-S2 governance contract that keeps production and development lanes separate and blocks production writes without explicit promotion gates.",
    ),
    "s2g1x_probe_contract_v1": PhaseContract(
        contract_id="s2g1x_probe_contract_v1",
        contract_version="1",
        phase_kind="gpu_ai_tagging_probe_and_s3a_integration_decision",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "capability_probe.completed",
            "capability_probe.safe_probe.no_production_db_writes",
            "capability_probe.safe_probe.no_media_tags_writes",
            "capability_probe.safe_probe.no_model_download",
            "capability_probe.safe_probe.local_files_only",
            "capability_probe.model_identity.model_name",
            "capability_probe.current_app_backend.forced_provider",
            "capability_probe.provider_matrix.cpu.available",
            "capability_probe.thresholds.general_threshold",
            "capability_probe.thresholds.character_threshold",
            "load_control.recommended_config.batch_size",
            "load_control.recommended_config.worker_count",
            "load_control.recommended_config.max_concurrent_jobs",
            "s3a_dev_dry_run_plan.production_execution_enabled",
            "s3a_dev_dry_run_plan.unattended_enabled",
            "s2g_s3a_decision.decision",
            "s2g_s3a_decision.should_share_job_progress_throttle_ledger_architecture",
            "s2g_s3a_decision.production_s3a_execution_enabled",
            "public_redaction.passed",
            "safety.production_ai_tagging",
            "safety.production_s3a_execution_enabled",
            "safety.unattended_auto_sync_enabled",
        ),
        required_validation_commands=(
            "python scripts/run_s2g1_ai_tagging_capability_probe.py --allow-model-load --synthetic-samples 3",
            "python scripts/check_phase_contract.py --contract s2g1x_probe_contract_v1 --summary docs/reports/s2g1x-gpu-ai-tagging-probe-summary.json",
            "pytest tests/test_s2g_s3a_job_control.py tests/test_s2g1_ai_tagging_capability_probe.py -v",
        ),
        forbidden_stages=(
            "production_import",
            "production_classification",
            "production_ai_tagging",
            "production_localization",
            "production_s3a_execution",
            "unattended_auto_sync",
            "provider_call",
            "pixiv",
            "gallery_dl",
            "saucenao",
            "google",
            "sourceconcept",
            "entity_bridge",
            "confirmed_entity_assignment",
            "cleanup_delete_reset_drop_truncate",
            "model_download",
        ),
        db_write_policy="forbidden; probe must not open a DB connection or write media_tags",
        provider_policy="local ONNX runtime only; no network model download or external provider calls",
        llm_policy="forbidden",
        mutation_policy="no production DB/storage/source/iCloud/app-managed mutation",
        redaction_policy="public report and JSON aggregate-only with local paths redacted",
        route_decision_policy="may decide shared foundation only; must not enable production S3A execution",
        failure_behavior="fail_closed_on_model_download_or_production_execution_claim",
        custom_checks=("s2g1x_probe",),
        description="S2G-1X contract for a safe GPU AI tagging capability probe plus S2G/S3A shared-architecture decision without production writes.",
    ),
    "s2g_s3a_f1_foundation_contract_v1": PhaseContract(
        contract_id="s2g_s3a_f1_foundation_contract_v1",
        contract_version="1",
        phase_kind="wd_tagger_provider_load_control_shared_foundation",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "wd_tagger.provider_abstraction.implemented",
            "wd_tagger.provider_abstraction.hardcoded_cpu_provider_removed",
            "wd_tagger.provider_abstraction.requested_provider_preference",
            "wd_tagger.provider_abstraction.available_onnx_providers",
            "wd_tagger.provider_abstraction.actual_provider",
            "wd_tagger.provider_abstraction.fallback_occurred",
            "wd_tagger.load_control.configured_batch_size",
            "wd_tagger.load_control.effective_batch_size",
            "wd_tagger.load_control.batch_size",
            "wd_tagger.load_control.batch.batch_cap_source",
            "wd_tagger.load_control.cpu_intra_op_threads",
            "wd_tagger.load_control.cpu_inter_op_threads",
            "wd_tagger.load_control.preprocess_workers",
            "wd_tagger.load_control.execution_mode",
            "wd_tagger.provenance.fields_available",
            "gpu_directml_enablement.attempted",
            "gpu_directml_enablement.package_install.performed",
            "gpu_directml_enablement.available_onnx_providers_after_attempt",
            "gpu_directml_enablement.success",
            "benchmarks.cpu.status",
            "shared_foundation.module",
            "shared_foundation.concepts",
            "s3a_dry_run_plan.production_execution_enabled",
            "s3a_dry_run_plan.unattended_enabled",
            "s3a_dry_run_plan.stages",
            "public_redaction.passed",
            "safety.production_db_writes",
            "safety.production_import",
            "safety.production_classification",
            "safety.production_ai_tagging",
            "safety.production_localization",
            "safety.production_s3a_execution_enabled",
            "safety.unattended_auto_sync_enabled",
        ),
        required_validation_commands=(
            "python scripts/run_s2g_s3a_f1_provider_load_smoke.py",
            "python scripts/check_phase_contract.py --contract s2g_s3a_f1_foundation_contract_v1 --summary docs/reports/s2g-s3a-f1-provider-load-control-foundation-summary.json",
            "pytest tests/test_ai_tagging_provider_foundation.py tests/test_phase_contracts.py -v",
        ),
        forbidden_stages=(
            "production_import",
            "production_classification",
            "production_ai_tagging",
            "production_localization",
            "production_s3a_execution",
            "unattended_auto_sync",
            "provider_call",
            "pixiv",
            "gallery_dl",
            "saucenao",
            "google",
            "sourceconcept",
            "entity_bridge",
            "confirmed_entity_assignment",
            "cleanup_delete_reset_drop_truncate",
            "model_download",
            "db_migration",
        ),
        db_write_policy="forbidden except existing job records from separately approved callers; this phase does not add production writes",
        provider_policy="local ONNX runtime provider selection only; DirectML/CUDA package install allowed only inside the project venv and must be reported",
        llm_policy="forbidden",
        mutation_policy="no production DB/storage/source/iCloud/app-managed mutation",
        redaction_policy="public report and JSON aggregate-only with local paths redacted",
        route_decision_policy="may provide S3A dry-run foundation only; must not enable production S3A or unattended S3B",
        failure_behavior="fail_closed_on_missing_actual_provider_fallback_reason_or_s3a_execution_enabled",
        custom_checks=("s2g_s3a_f1_foundation",),
        description="S2G/S3A-F1 contract for WDTagger provider abstraction, bounded load control, provenance, and dry-run-only shared job vocabulary.",
    ),
    "s2g_real1_bounded_ai_tagging_validation_contract_v1": PhaseContract(
        contract_id="s2g_real1_bounded_ai_tagging_validation_contract_v1",
        contract_version="1",
        phase_kind="bounded_real_ai_tagging_validation",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "pipeline_contract.status",
            "run_configuration.max_items",
            "run_configuration.write_requested",
            "run_configuration.operator_confirmation_exact",
            "run_configuration.local_files_only",
            "run_configuration.model_download_allowed",
            "selected_media.count",
            "selected_media.no_full_library_fallback",
            "selected_media.private_locator_values_recorded",
            "model_cache.local_files_only",
            "dry_run.executed",
            "dry_run.selected_media_count",
            "dry_run.predicted_tag_count",
            "dry_run.media_tags_count_delta",
            "primary_provider_validation.provider.actual_provider",
            "primary_provider_validation.provider_preference_requested",
            "cpu_fallback_validation.executed",
            "cpu_fallback_validation.provider.actual_provider",
            "write_prerequisites.all_passed",
            "write_prerequisites.primary_dry_run_success",
            "write_prerequisites.cpu_fallback_success",
            "write_prerequisites.exact_write_confirmation_present",
            "write_prerequisites.write_executed_after_prerequisites_passed",
            "load_control_observations.effective_batch_size",
            "load_control_observations.cpu_intra_op_threads",
            "load_control_observations.cpu_inter_op_threads",
            "load_control_observations.preprocess_workers",
            "load_control_observations.max_concurrent_ai_jobs",
            "write_run.executed",
            "write_run.status",
            "write_run.failed",
            "write_run.processed",
            "write_run.media_tags_count_delta",
            "s3a_boundary.production_execution_enabled",
            "s3a_boundary.unattended_enabled",
            "public_redaction.passed",
            "safety.no_full_library_run",
            "safety.production_s3a_execution_enabled",
            "safety.unattended_s3b_enabled",
            "safety.provider_pixiv_gallery_dl_saucenao_google_calls",
            "safety.provider_pixiv_r1r_entity_operations",
            "safety.sourceconcept_r1r_r2",
            "safety.entity_bridge",
            "safety.cleanup_delete_reset_drop_truncate",
            "safety.model_download",
        ),
        required_validation_commands=(
            "python scripts/run_s2g_real1_bounded_ai_tagging_validation.py",
            "python scripts/check_phase_contract.py --contract s2g_real1_bounded_ai_tagging_validation_contract_v1 --summary docs/reports/s2g-real1-bounded-ai-tagging-validation-summary.json",
            "pytest tests/test_phase_contracts.py tests/test_s2g_real1_bounded_ai_tagging_validation.py -v",
        ),
        forbidden_stages=(
            "full_library_ai_tagging",
            "production_s3a_execution",
            "unattended_s3b",
            "provider_call",
            "pixiv",
            "gallery_dl",
            "saucenao",
            "google",
            "sourceconcept",
            "r1r",
            "entity_bridge",
            "confirmed_entity_assignment",
            "desired_media_backfill",
            "cleanup_delete_reset_drop_truncate",
            "db_import",
            "production_classification",
            "production_localization",
            "model_download",
        ),
        db_write_policy="dry-run must not write media_tags; bounded write requires exact operator confirmation and max_items <= 5",
        provider_policy="local ONNX runtime only; DirectML preferred with CPU fallback validation; no external provider calls",
        llm_policy="forbidden",
        mutation_policy="no source/iCloud/app-managed mutation and no cleanup/delete/reset/drop/truncate",
        redaction_policy="public report and JSON aggregate-only with no paths, filenames, source URLs, or secrets",
        failure_behavior="fail_closed_on_full_library_scope_missing_provider_missing_cpu_fallback_or_unapproved_write",
        custom_checks=("s2g_real1_bounded_ai_tagging_validation",),
        description="S2G-REAL1 contract for bounded real-media AI tagging validation under DirectML/CPU provider controls without S3A production execution.",
    ),
    "s3a_pilot1_new_data_directml_chain_contract_v1": PhaseContract(
        contract_id="s3a_pilot1_new_data_directml_chain_contract_v1",
        contract_version="1",
        phase_kind="controlled_new_data_directml_chain_pilot",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "pipeline_contract.status",
            "run_configuration.input_mode",
            "run_configuration.max_items",
            "run_configuration.local_files_only",
            "run_configuration.model_download_allowed",
            "run_configuration.import_write_requested",
            "run_configuration.import_confirmation_exact",
            "run_configuration.ai_tagging_write_requested",
            "run_configuration.ai_tagging_confirmation_exact",
            "scope.selected_count",
            "scope.over_cap_count",
            "scope.no_full_library_fallback",
            "scope.private_locator_values_recorded",
            "model_cache.local_files_only",
            "model_cache.status",
            "import_write_preconditions.passed",
            "import_write_preconditions.blockers",
            "import_reuse.reported",
            "import_reuse.imported_count",
            "import_reuse.reused_count",
            "import_reuse.skipped_count",
            "import_reuse.failed_count",
            "classification.reported",
            "classification.classified_count",
            "classification.reused_classification_count",
            "classification.failed_count",
            "classification.content_class_distribution",
            "directml_ai_tagging.reported",
            "directml_ai_tagging.dry_run",
            "directml_ai_tagging.provider",
            "directml_ai_tagging.media_tags_count_before",
            "directml_ai_tagging.media_tags_count_after",
            "directml_ai_tagging.media_tags_count_delta",
            "directml_ai_tagging.tags_added",
            "directml_ai_tagging.suggestions_added",
            "directml_ai_tagging.skipped_locked",
            "directml_ai_tagging.ignored_low_confidence",
            "directml_ai_tagging.failed",
            "directml_ai_tagging.first_time_media_tag_insertion_proven",
            "cpu_fallback_validation.reported",
            "cpu_fallback_validation.executed",
            "cpu_fallback_validation.status",
            "cpu_fallback_validation.dry_run",
            "cpu_fallback_validation.failed",
            "cpu_fallback_validation.media_tags_count_delta",
            "cpu_fallback_validation.provider",
            "localization.reported",
            "localization.reused_translations",
            "localization.new_translations",
            "localization.failed",
            "localization.llm_external_provider_used",
            "s3a_boundary.operator_triggered_pilot_only",
            "s3a_boundary.production_execution_enabled",
            "s3a_boundary.unattended_enabled",
            "public_redaction.passed",
            "safety.max_items_lte_5",
            "safety.selected_input_explicit_bounded",
            "safety.no_full_library_run",
            "safety.provider_pixiv_gallery_dl_saucenao_google_calls",
            "safety.sourceconcept_r1_r2_r1r",
            "safety.entity_bridge",
            "safety.cleanup_delete_reset_drop_truncate",
        ),
        required_validation_commands=(
            "python scripts/run_s3a_pilot1_new_data_directml_chain.py --input-path <explicit staging path>",
            "python scripts/check_phase_contract.py --contract s3a_pilot1_new_data_directml_chain_contract_v1 --summary docs/reports/s3a-pilot1-new-data-directml-chain-summary.json",
            "pytest tests/test_phase_contracts.py tests/test_s3a_pilot1_new_data_directml_chain.py -v",
        ),
        forbidden_stages=(
            "full_library_import",
            "full_library_ai_tagging",
            "production_s3a_execution",
            "unattended_s3b",
            "scheduled_automation",
            "provider_call",
            "pixiv",
            "gallery_dl",
            "saucenao",
            "google",
            "sourceconcept",
            "r1",
            "r2",
            "r1r",
            "entity_bridge",
            "confirmed_entity_assignment",
            "desired_media_backfill",
            "cleanup_delete_reset_drop_truncate",
            "model_download",
        ),
        db_write_policy="tiny import and media_tags writes only after exact operator confirmations; max_items <= 5; dry-run/preflight first",
        provider_policy="local ONNX runtime only; DirectML preferred with CPU fallback validation; no external provider calls",
        llm_policy="forbidden unless a later explicit provider policy approves it; this contract expects localization reuse/defer only",
        mutation_policy="no source/iCloud mutation, no cleanup/delete/reset/drop/truncate, no broad production sync",
        redaction_policy="public report and JSON aggregate-only with no absolute paths, private filenames, media IDs, secrets, source URLs, or provider tokens",
        route_decision_policy="operator-triggered pilot only; must not enable production S3A or unattended S3B",
        failure_behavior="fail_closed_on_unbounded_scope_full_library_fallback_missing_provider_missing_cpu_fallback_unapproved_write_or_redaction_failure",
        custom_checks=("s3a_pilot1_new_data_directml_chain",),
        description="S3A-PILOT1 contract for a tiny operator-triggered new-data import/reuse, classification, DirectML AI tagging, and localization validation chain without production automation.",
    ),
    "s3a_prod1_operator_incremental_sync_contract_v1": PhaseContract(
        contract_id="s3a_prod1_operator_incremental_sync_contract_v1",
        contract_version="1",
        phase_kind="operator_triggered_production_incremental_sync_guard",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "pipeline_contract.status",
            "run_configuration.input_mode",
            "run_configuration.max_items",
            "run_configuration.local_files_only",
            "run_configuration.model_download_allowed",
            "run_configuration.production_write_requested",
            "run_configuration.exact_production_sync_confirmation",
            "run_configuration.single_operator_triggered_run_only",
            "run_configuration.no_full_library_fallback",
            "scope.explicit_input_path_supplied",
            "scope.selected_count",
            "scope.over_cap_count",
            "scope.no_full_library_fallback",
            "scope.private_locator_values_recorded",
            "scope.protected_input_gate.reported",
            "scope.protected_input_gate.passed",
            "scope.source_safety_gate.reported",
            "scope.source_safety_gate.passed",
            "scope.source_safety_gate.read_probe_used",
            "scope.source_safety_gate.hydration_policy_enabled",
            "preflight.input_mode",
            "preflight.discovered_supported_files",
            "preflight.over_cap_check.passed",
            "preflight.model_cache.status",
            "preflight.model_cache.model_download_performed",
            "preflight.provider_availability.reported",
            "preflight.directml_available",
            "preflight.cpu_fallback_available",
            "preflight.protected_input_gate.reported",
            "preflight.source_safety_gate.reported",
            "preflight.no_full_library_fallback",
            "preflight.public_private_path_redaction.absolute_paths_redacted",
            "preflight.public_private_path_redaction.file_labels_redacted",
            "model_cache.local_files_only",
            "model_cache.status",
            "model_cache.model_download_allowed",
            "model_cache.model_download_performed",
            "db_session.available",
            "import_write_preconditions.passed",
            "import_write_preconditions.blockers",
            "import_write_preconditions.provider_preference_dml_then_cpu",
            "import_write_preconditions.protected_input_gate_passed",
            "import_write_preconditions.source_safety_gate_passed",
            "import_reuse.reported",
            "import_reuse.imported_count",
            "import_reuse.reused_count",
            "import_reuse.skipped_count",
            "import_reuse.failed_count",
            "import_reuse.app_managed_storage_writes",
            "classification.reported",
            "classification.classified_count",
            "classification.reused_classification_count",
            "classification.failed_count",
            "classification.content_class_distribution",
            "directml_provider_probe.reported",
            "directml_provider_probe.executed",
            "directml_provider_probe.status",
            "directml_provider_probe.failed",
            "directml_provider_probe.rollback_error",
            "directml_provider_probe.error_state",
            "directml_provider_probe.provider",
            "provider_write_gate.reported",
            "provider_write_gate.write_allowed",
            "provider_write_gate.provider_preference_dml_then_cpu",
            "provider_write_gate.blockers",
            "directml_ai_tagging.reported",
            "directml_ai_tagging.dry_run",
            "directml_ai_tagging.provider",
            "directml_ai_tagging.provider_preference_requested",
            "directml_ai_tagging.media_tags_count_before",
            "directml_ai_tagging.media_tags_count_after",
            "directml_ai_tagging.media_tags_count_delta",
            "directml_ai_tagging.media_with_ai_tags_delta",
            "directml_ai_tagging.tags_added",
            "directml_ai_tagging.suggestions_added",
            "directml_ai_tagging.skipped_locked",
            "directml_ai_tagging.ignored_low_confidence",
            "directml_ai_tagging.failed",
            "directml_ai_tagging.first_time_media_tag_insertion_proven",
            "cpu_fallback_validation.reported",
            "cpu_fallback_validation.executed",
            "cpu_fallback_validation.status",
            "cpu_fallback_validation.dry_run",
            "cpu_fallback_validation.failed",
            "cpu_fallback_validation.media_tags_count_delta",
            "cpu_fallback_validation.provider",
            "localization.reported",
            "localization.candidate_tags_count",
            "localization.reused_translations",
            "localization.new_translations",
            "localization.missing_or_deferred",
            "localization.failed",
            "localization.llm_external_provider_used",
            "s3a_boundary.operator_triggered_production_sync_enabled",
            "s3a_boundary.single_operator_triggered_run_only",
            "s3a_boundary.production_automation_enabled",
            "s3a_boundary.scheduled_automation_enabled",
            "s3a_boundary.unattended_s3b_enabled",
            "validation.production_write_completed",
            "public_reports.summary_json_path",
            "public_reports.markdown_report_path",
            "public_redaction.passed",
            "safety.max_items_lte_5",
            "safety.explicit_input_required",
            "safety.no_full_library_run",
            "safety.single_operator_triggered_run_only",
            "safety.production_automation_enabled",
            "safety.unattended_s3b_enabled",
            "safety.scheduled_automation_enabled",
            "safety.provider_pixiv_gallery_dl_saucenao_google_calls",
            "safety.sourceconcept_r1_r2_r1r",
            "safety.entity_bridge",
            "safety.cleanup_delete_reset_drop_truncate",
        ),
        required_validation_commands=(
            "python scripts/run_s3a_prod1_operator_incremental_sync_guard.py --input-path <explicit input path>",
            "python scripts/run_s3a_prod1_operator_incremental_sync_guard.py --input-path <explicit input path> --production-sync-confirmation <exact confirmation>",
            "python scripts/check_phase_contract.py --contract s3a_prod1_operator_incremental_sync_contract_v1 --summary docs/reports/s3a-prod1-operator-incremental-sync-summary.json",
            "pytest tests/test_s3a_prod1_operator_incremental_sync_guard.py -v",
        ),
        forbidden_stages=(
            "full_library_import",
            "full_library_ai_tagging",
            "unattended_s3b",
            "scheduled_automation",
            "provider_call",
            "pixiv",
            "gallery_dl",
            "saucenao",
            "google",
            "sourceconcept",
            "r1",
            "r2",
            "r1r",
            "entity_bridge",
            "confirmed_entity_assignment",
            "desired_media_backfill",
            "cleanup_delete_reset_drop_truncate",
            "model_download",
        ),
        db_write_policy="tiny input-path import/reuse and media_tags writes only after the exact S3A-PROD1 production sync confirmation; max_items <= 5",
        provider_policy="local ONNX runtime only; DirectML must be the write provider, with CPU fallback validated dry-run; no external provider calls",
        llm_policy="forbidden unless a later explicit provider policy approves it; this contract expects touched-tag localization reuse/defer only",
        mutation_policy="no source/iCloud mutation, no cleanup/delete/reset/drop/truncate, no broad production sync, no scheduled automation",
        redaction_policy="public report and JSON aggregate-only with no absolute paths, private filenames, media IDs, secrets, source URLs, or provider tokens",
        route_decision_policy="single operator-triggered production run only; scheduled S3A and unattended S3B remain disabled",
        failure_behavior="fail_closed_on_missing_explicit_input_unbounded_scope_full_library_fallback_unapproved_write_missing_directml_missing_cpu_fallback_or_redaction_failure",
        custom_checks=("s3a_prod1_operator_incremental_sync",),
        description="S3A-PROD1 contract for a guarded operator-triggered production incremental sync path from explicit input through import/reuse, classification, DirectML AI tagging, localization reuse/defer, and public redacted summary.",
    ),
    "s3a_prod2_s3b_d1_operator_scaleup_disabled_sync_contract_v1": PhaseContract(
        contract_id="s3a_prod2_s3b_d1_operator_scaleup_disabled_sync_contract_v1",
        contract_version="1",
        phase_kind="bounded_operator_sync_scaleup_disabled_unattended_scaffold",
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "pipeline_contract.status",
            "run_configuration.input_mode",
            "run_configuration.max_items",
            "run_configuration.local_files_only",
            "run_configuration.model_download_allowed",
            "run_configuration.write_requested",
            "run_configuration.operator_confirmation_exact",
            "run_configuration.provider_preference_requested",
            "run_configuration.min_stable_age_seconds",
            "run_configuration.stability_wait_seconds",
            "scope.selected_count",
            "scope.over_cap_count",
            "scope.missing_input_count",
            "scope.no_full_library_fallback",
            "scope.protected_input_gate.reported",
            "scope.protected_input_gate.passed",
            "scope.protected_input_gate.blocked_count",
            "scope.private_locator_values_recorded",
            "protected_input_gate.reported",
            "source_file_preflight.reported",
            "source_file_preflight.eligible_count",
            "source_file_preflight.skipped_count",
            "source_file_preflight.failed_count",
            "source_file_preflight.cloud_placeholder_skipped",
            "model_cache.local_files_only",
            "model_cache.status",
            "provider_availability.directml_available",
            "provider_availability.cpu_fallback_available",
            "job_concurrency.no_concurrent_import_or_tagging_jobs",
            "write_preconditions.passed",
            "write_preconditions.blockers",
            "write_preconditions.provider_preference_dml_then_cpu",
            "write_preconditions.protected_input_gate_passed",
            "write_preconditions.cpu_fallback_available",
            "write_preconditions.s3b_disabled_state_passed",
            "write_provider_policy.reported",
            "write_provider_policy.actual_write_provider_preference",
            "write_provider_policy.cpu_fallback_write_allowed",
            "write_provider_policy.provider_fallback_disabled_for_actual_write",
            "write_window_protection.reported",
            "write_window_protection.mode",
            "write_window_protection.durable_lock_held",
            "write_window_protection.write_window_rechecked",
            "write_window_protection.no_concurrent_import_or_tagging_jobs",
            "write_window_protection.import_recheck.passed",
            "write_window_protection.ai_write_recheck.passed",
            "import_reuse.reported",
            "import_reuse.imported_count",
            "import_reuse.reused_count",
            "import_reuse.skipped_count",
            "import_reuse.failed_count",
            "classification.reported",
            "classification.classified_count",
            "classification.reused_classification_count",
            "classification.failed_count",
            "classification.content_class_distribution",
            "directml_provider_probe.reported",
            "directml_provider_probe.dry_run",
            "directml_provider_probe.failed",
            "directml_provider_probe.media_tags_count_delta",
            "provider_write_gate.reported",
            "provider_write_gate.write_allowed",
            "provider_write_gate.provider_preference_dml_then_cpu",
            "provider_write_gate.probe_executed",
            "directml_ai_tagging.reported",
            "directml_ai_tagging.dry_run",
            "directml_ai_tagging.provider",
            "directml_ai_tagging.media_tags_count_before",
            "directml_ai_tagging.media_tags_count_after",
            "directml_ai_tagging.media_tags_count_delta",
            "directml_ai_tagging.media_with_ai_tags_delta",
            "directml_ai_tagging.first_time_media_tag_insertion_count",
            "directml_ai_tagging.tags_added",
            "directml_ai_tagging.suggestions_added",
            "directml_ai_tagging.skipped_locked",
            "directml_ai_tagging.ignored_low_confidence",
            "directml_ai_tagging.failed",
            "cpu_fallback_validation.reported",
            "cpu_fallback_validation.executed",
            "cpu_fallback_validation.status",
            "cpu_fallback_validation.dry_run",
            "cpu_fallback_validation.failed",
            "cpu_fallback_validation.media_tags_count_delta",
            "cpu_fallback_validation.provider",
            "localization.reported",
            "localization.reused_translations",
            "localization.new_translations",
            "localization.failed",
            "localization.llm_external_provider_used",
            "failure_budget.passed",
            "s3a_boundary.operator_triggered_only",
            "s3a_boundary.production_execution_enabled",
            "s3a_boundary.unattended_enabled",
            "s3b_disabled_scaffold.status",
            "s3b_disabled_scaffold.policy.unattended_enabled",
            "s3b_disabled_scaffold.policy.scheduled_enabled",
            "s3b_disabled_scaffold.policy.dry_run_only",
            "s3b_disabled_scaffold.policy.require_operator_confirmation",
            "s3b_disabled_scaffold.policy.no_full_library_fallback",
            "s3b_disabled_scaffold.policy.private_paths_excluded_from_public_report",
            "s3b_disabled_scaffold.trigger.scheduler_started",
            "s3b_disabled_scaffold.trigger.background_job_started",
            "s3b_disabled_scaffold.watermark.identity_strategy",
            "s3b_disabled_scaffold.cloud_file_policy.paths_redacted",
            "public_redaction.passed",
            "safety.max_items_lte_20",
            "safety.selected_input_explicit_bounded",
            "safety.no_full_library_run",
            "safety.provider_pixiv_gallery_dl_saucenao_google_calls",
            "safety.sourceconcept_r1_r2_r1r",
            "safety.entity_bridge",
            "safety.cleanup_delete_reset_drop_truncate",
        ),
        required_validation_commands=(
            "python scripts/run_s3a_prod2_bounded_operator_sync_scaleup.py --input-path <explicit staging path>",
            "python scripts/check_phase_contract.py --contract s3a_prod2_s3b_d1_operator_scaleup_disabled_sync_contract_v1 --summary docs/reports/s3a-prod2-s3b-d1-operator-scaleup-disabled-sync-summary.json",
            "pytest tests/test_s3a_prod2_s3b_d1_operator_scaleup_disabled_sync.py -v",
        ),
        forbidden_stages=(
            "full_library_import",
            "full_library_ai_tagging",
            "unattended_s3b_enabled",
            "scheduled_automation_enabled",
            "scheduler_started",
            "background_sync_started",
            "provider_call",
            "pixiv",
            "gallery_dl",
            "saucenao",
            "google",
            "sourceconcept",
            "r1",
            "r2",
            "r1r",
            "entity_bridge",
            "confirmed_entity_assignment",
            "desired_media_backfill",
            "cleanup_delete_reset_drop_truncate",
            "model_download",
        ),
        db_write_policy="operator-triggered import/media_tags writes only after exact confirmation; max_items <= 20; no scheduler or unattended writes",
        provider_policy="local ONNX runtime only; DirectML preferred with CPU fallback validation; no external provider calls",
        llm_policy="forbidden unless a later explicit provider policy approves it; this contract expects localization reuse/defer only",
        mutation_policy="no source/iCloud mutation, no cleanup/delete/reset/drop/truncate, no broad production sync, no automatic writes",
        redaction_policy="public report and JSON aggregate-only with no absolute paths, private filenames, media IDs, secrets, source URLs, or provider tokens",
        route_decision_policy="operator-triggered bounded scale-up plus disabled S3B scaffold only; scheduled/unattended sync must remain disabled",
        failure_behavior="fail_closed_on_unbounded_scope_full_library_fallback_missing_provider_missing_cpu_fallback_unapproved_write_enabled_scheduler_or_redaction_failure",
        custom_checks=("s3a_prod2_s3b_d1_operator_scaleup_disabled_sync",),
        description="S3A-PROD2/S3B-D1 contract for bounded operator-triggered production sync scale-up plus disabled-by-default unattended/scheduled sync scaffold.",
    ),
    "source_concept_full_chain_contract_v1": PhaseContract(
        contract_id="source_concept_full_chain_contract_v1",
        contract_version="1",
        phase_kind="source_concept_full_chain_replay",
        required_inputs=(
            "SC1 full-chain resolver contract evidence",
            "R1/R1R source/tag/source-metadata input inventory",
        ),
        required_stages=SOURCE_CONCEPT_FULL_CHAIN_STAGES,
        forbidden_stages=(
            "entity_truth_promotion",
            "media_tags_mutation",
            "provider_enrichment_call",
            "image_upload",
        ),
        required_artifacts=("validation_pack", "review_pack", "mutation_proof", "post_commit_verification"),
        required_summary_fields=(
            "pipeline_contract.contract_id",
            "required_stages",
            "executed_stages",
            "missing_required_stages",
            "full_chain_fidelity_passed",
            "deterministic_stage_summary",
            "llm_adjudication_plan",
            "llm_adjudication_used",
            "llm_judgment_count",
            "llm_max_calls",
            "llm_budget_usd",
            "llm_provider_mode",
            "llm_cache_summary",
            "mutation_proof",
            "post_commit_verification",
            "conclusion",
        ),
        db_write_policy="allowed_source_concept_tables_only_after_dry_run_and_approval",
        provider_policy="no provider/source enrichment; provider identity only for LLM adjudication if approved",
        llm_policy="required_for_full_chain_unless zero eligible proof or blocked status is explicit",
        mutation_policy="source_layer_only_no_entity_truth_no_media_tags",
        redaction_policy="public aggregate/redacted labels only",
        review_pack_policy="required",
        artifact_lifecycle_policy="validation pack private; public report redacted",
        route_decision_policy="cannot approve downstream route unless full_chain_fidelity_passed is true",
        failure_behavior="fail_or_block_before_claiming_target_met",
        custom_checks=("source_concept_full_chain",),
        description="Critical R1R contract: deterministic SourceConcept resolver plus bounded LLM pair adjudication proof.",
    ),
    "review_pack_contract_v1": PhaseContract(
        contract_id="review_pack_contract_v1",
        contract_version="1",
        phase_kind="review_pack",
        required_artifacts=("manifest.json", "checksums.json", "redaction-report", "public-report-copy", "zip"),
        provider_policy="forbidden",
        llm_policy="forbidden",
        mutation_policy="local_ignored_artifact_only",
        redaction_policy="final file set must be scanned before zip success",
        review_pack_policy="manifest_checksums_redaction_public_copy_required",
        artifact_lifecycle_policy="zip generated but not committed",
        failure_behavior="fail_closed_on_missing_manifest_checksum_or_redaction_scan",
        custom_checks=("review_pack",),
        description="Checks review pack manifest, checksums, final redaction scan, and private-label safety.",
    ),
    "route_audit_contract_v1": PhaseContract(
        contract_id="route_audit_contract_v1",
        contract_version="1",
        phase_kind="route_audit",
        required_summary_fields=("final_route_decision_status", "transaction_readonly_proof", "mutation_proof"),
        required_artifacts=("public_report", "summary_json", "review_pack"),
        db_write_policy="read_only_repeatable_read_or_serializable",
        provider_policy="forbidden",
        llm_policy="forbidden",
        mutation_policy="no_db_or_source_mutation",
        redaction_policy="public report and summary must be scanned",
        review_pack_policy="required_unless_waived; incident gate overrides pack audit",
        route_decision_policy="route approval blocked if upstream pipeline contract failed or incomplete",
        failure_behavior="fail_closed_on_write_or_upstream_pipeline_gap",
        custom_checks=("route_audit",),
        description="Checks read-only route audits and blocks route approval when upstream contracts are incomplete.",
    ),
    "public_redaction_contract_v1": PhaseContract(
        contract_id="public_redaction_contract_v1",
        contract_version="1",
        phase_kind="public_artifact_redaction",
        provider_policy="forbidden",
        llm_policy="forbidden",
        mutation_policy="no_mutation",
        redaction_policy="scan Markdown and JSON keys plus values for secrets, paths, filenames, and private provenance",
        failure_behavior="fail_before_public_artifact_write",
        custom_checks=("public_redaction",),
        description="Scans public Markdown/JSON payloads for secrets, local paths, and private provenance leakage.",
    ),
    "mutation_safety_contract_v1": PhaseContract(
        contract_id="mutation_safety_contract_v1",
        contract_version="1",
        phase_kind="mutation_safety",
        required_summary_fields=("mutation_proof",),
        db_write_policy="table_allowlist_denylist_and_fingerprints_required",
        provider_policy="not_applicable",
        llm_policy="not_applicable",
        mutation_policy="before_after_fingerprints_and_post_commit_verification_for_write_phases",
        failure_behavior="rollback_or_fail_closed_on_unexpected_forbidden_change",
        custom_checks=("mutation_safety",),
        description="Checks table allowlist/denylist, before/after fingerprints, forbidden table stability, and destructive-operation bans.",
    ),
    "artifact_lifecycle_contract_v1": PhaseContract(
        contract_id="artifact_lifecycle_contract_v1",
        contract_version="1",
        phase_kind="artifact_lifecycle",
        required_summary_fields=("artifact_lifecycle",),
        provider_policy="not_applicable",
        llm_policy="not_applicable",
        mutation_policy="private_artifacts_ignored_public_artifacts_redacted",
        redaction_policy="public artifacts must pass public_redaction_contract_v1",
        artifact_lifecycle_policy="production,durable validation,reusable validation,phase-scoped,one-off local/private,public report",
        failure_behavior="fail_closed_on_private_artifact_commit_or_unredacted_public_report",
        custom_checks=("artifact_lifecycle",),
        description="Classifies artifacts and enforces committed/private/public boundaries.",
    ),
    "destructive_operation_contract_v1": PhaseContract(
        contract_id="destructive_operation_contract_v1",
        contract_version="1",
        phase_kind="destructive_operation",
        required_summary_fields=("destructive_operation",),
        db_write_policy="destructive_explicit_approval_only",
        provider_policy="not_applicable",
        llm_policy="not_applicable",
        mutation_policy="dry_run_backup_exact_target_no_wildcard_post_verify_required",
        failure_behavior="blocking_contract_fails_without_explicit_approval_and_dry_run",
        custom_checks=("destructive_operation",),
        description="Blocking contract for any delete/reset/drop/truncate or other destructive operation.",
    ),
    "entity_truth_bridge_contract_v1": PhaseContract(
        contract_id="entity_truth_bridge_contract_v1",
        contract_version="1",
        phase_kind="entity_truth_bridge",
        required_summary_fields=("entity_truth_bridge",),
        db_write_policy="route_approved_preview_manual_confirmation_audit_rollback_write_guards_required",
        provider_policy="not_applicable",
        llm_policy="not_applicable",
        mutation_policy="no_direct_sourceconcept_to_entity_truth_promotion_without_contract",
        route_decision_policy="requires approved upstream route",
        failure_behavior="fail_closed_without_preview_manual_audit_rollback_gates",
        custom_checks=("entity_truth_bridge",),
        description="Defines future Entity bridge proof requirements. GOV3 does not implement the bridge.",
    ),
}


def get_contract(contract_id: str) -> PhaseContract:
    try:
        return CONTRACTS[contract_id]
    except KeyError as exc:
        known = ", ".join(sorted(CONTRACTS))
        raise KeyError(f"Unknown contract_id {contract_id!r}. Known contracts: {known}") from exc


def list_contracts() -> list[PhaseContract]:
    return [CONTRACTS[contract_id] for contract_id in sorted(CONTRACTS)]
